# Generated by Django 5.0.6 on 2024-06-28 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdbb3df5-28bc-4f09-a75c-0da07b515c63'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdbb3df5-28bc-4f09-a75c-0da07b515c63'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdbb3df5-28bc-4f09-a75c-0da07b515c63'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdbb3df5-28bc-4f09-a75c-0da07b515c63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
