# Generated by Django 5.0.6 on 2024-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_category_id_alter_food_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='total_price_field',
        ),
    ]
