# Generated by Django 5.0.6 on 2024-07-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_remove_foodorder_total_price_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='discounted_price_field',
        ),
    ]
