# Generated by Django 5.0.6 on 2024-07-02 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_food_discounted_price_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'courier',
                'verbose_name_plural': 'couriers',
                'db_table': 'courier',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='discounted_price_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='total_price_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foods.courier'),
        ),
    ]
