# Generated by Django 5.0 on 2024-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_courier_food_discounted_price_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
