# Generated by Django 5.0.6 on 2024-06-28 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c43690ce-3601-4a4b-a730-0f983ddb8140'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c43690ce-3601-4a4b-a730-0f983ddb8140'), editable=False, primary_key=True, serialize=False),
        ),
    ]
