# Generated by Django 5.0.6 on 2024-06-28 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('248e85d7-9d33-4ba9-8b4d-5a64472fae04'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('248e85d7-9d33-4ba9-8b4d-5a64472fae04'), editable=False, primary_key=True, serialize=False),
        ),
    ]
