# Generated by Django 5.0.6 on 2024-06-28 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bc6882e-6661-4848-af19-29ccb16a458c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bc6882e-6661-4848-af19-29ccb16a458c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
