# Generated by Django 5.0.6 on 2024-06-28 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23544422-1239-47ff-ac5e-bc3395434c3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23544422-1239-47ff-ac5e-bc3395434c3b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
