# Generated by Django 5.0.6 on 2024-07-01 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1bffe07-1ee1-4d0b-a3f2-e39a7360f33c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1bffe07-1ee1-4d0b-a3f2-e39a7360f33c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
