# Generated by Django 5.0.6 on 2024-07-01 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30d91843-02e3-484f-a27a-62eda068e0d8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30d91843-02e3-484f-a27a-62eda068e0d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
