# Generated by Django 5.0.6 on 2024-07-01 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c013f0a-ec61-48b0-ad9f-4db0d0c6f88e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c013f0a-ec61-48b0-ad9f-4db0d0c6f88e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
