# Generated by Django 5.0.6 on 2024-07-01 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c4a03ba-76e2-4207-9dd5-700ec4d8018b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c4a03ba-76e2-4207-9dd5-700ec4d8018b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
