# Generated by Django 5.0.6 on 2024-07-02 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef05248f-c035-4b4a-8b45-b7e1f5603fb1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef05248f-c035-4b4a-8b45-b7e1f5603fb1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
