# Generated by Django 5.0 on 2024-07-03 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b71ca959-6271-41f3-8660-b75b0fd97267'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b71ca959-6271-41f3-8660-b75b0fd97267'), editable=False, primary_key=True, serialize=False),
        ),
    ]
