# Generated by Django 5.0 on 2024-07-03 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d1208b9-167b-4c96-8c8a-ad97b59f0af3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d1208b9-167b-4c96-8c8a-ad97b59f0af3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
