# Generated by Django 5.0 on 2024-07-03 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8653f10-5a6c-4304-ba69-e571c7985d34'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8653f10-5a6c-4304-ba69-e571c7985d34'), editable=False, primary_key=True, serialize=False),
        ),
    ]
