# Generated by Django 5.0 on 2024-07-03 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('301fb5bb-f3b6-4fc4-869a-0c16c7e076f8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('301fb5bb-f3b6-4fc4-869a-0c16c7e076f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
