# Generated by Django 5.0 on 2024-07-03 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7d34e21-e412-44e6-bc5d-d9bd7ee8c8ca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7d34e21-e412-44e6-bc5d-d9bd7ee8c8ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
