# Generated by Django 5.0 on 2024-07-03 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a6daf0c-8c7f-4c6a-acaf-7aadb9cfecfa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a6daf0c-8c7f-4c6a-acaf-7aadb9cfecfa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
