# Generated by Django 5.0 on 2024-07-03 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('708c8cab-1c09-48ba-a34c-0bd1b17900b3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('708c8cab-1c09-48ba-a34c-0bd1b17900b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
