# Generated by Django 5.0 on 2024-07-03 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4340c9f-04c7-4deb-8a8c-fb7a74b6e821'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4340c9f-04c7-4deb-8a8c-fb7a74b6e821'), editable=False, primary_key=True, serialize=False),
        ),
    ]
