# Generated by Django 5.0 on 2024-07-03 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55f18b5f-cf71-4132-9fc3-0ab638279f8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55f18b5f-cf71-4132-9fc3-0ab638279f8f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
